listen              1935; # 容器内部RTMP端口，Compose映射为宿主机12935

# 1万主播仅发布连接就需要1万FD；额外预留API、播放和重连连接。
# 这只是连接硬上限，不代表单节点已经通过1万路编码/转封装压测；生产仍应按压测结果分片SRS。
max_connections     30000;

daemon              off; # 是否后台运行，Docker 中建议关闭，由 Docker 管理进程

srs_log_tank        console; # 日志输出到控制台，方便通过 docker logs 查看


# =========================
# HTTP 静态文件 / FLV / HLS 服务
# =========================
http_server {
    enabled         on; # 开启 HTTP 服务，用于 HTTP-FLV、HLS 等播放
    listen          8080; # 容器内部 HTTP 监听端口，对外映射为 18080
    dir             ./objs/nginx/html; # HTTP 静态文件目录，也是 HLS 文件默认生成目录
}


# =========================
# HTTP API
# =========================
http_api {
    enabled         on; # 开启 SRS HTTP API
    listen          1985; # 容器内部HTTP API端口，Compose映射为宿主机12985
}


# =========================
# SRS 统计
# =========================
stats {
    network         0; # 指定用于统计网络信息的网卡索引，0 通常表示第一张网卡
}


# =========================
# WebRTC Server
# =========================
rtc_server {
    enabled         on; # 开启 WebRTC 服务

    listen          8000; # WebRTC 媒体传输 UDP 端口，需要开放 UDP 8000

    candidate       $CANDIDATE; # WebRTC 对外暴露的 IP，Docker 启动时通过环境变量传入公网 IP
}


# =========================
# 默认虚拟主机
# =========================
vhost __defaultVhost__ {

    # =========================
    # WebRTC
    # =========================
    rtc {
        enabled         on; # 开启当前 vhost 的 WebRTC 功能

        rtmp_to_rtc     on; # 允许 RTMP 推流转换成 WebRTC，供 WebRTC 用户拉流

        rtc_to_rtmp     on; # 允许 WebRTC 推流转换成 RTMP
    }


    # =========================
    # HTTP-FLV
    # =========================
    http_remux {
        enabled         on; # 开启 RTMP 转 HTTP-FLV

        mount           [vhost]/[app]/[stream].flv; # HTTP-FLV 播放地址格式
    }


    # ============================================================
    # 【新增】HLS / m3u8
    # 默认 rtmp2rtc.conf 没有这一段
    # ============================================================
    hls {
        enabled         on; # 【新增】开启 HLS，生成 m3u8 和 ts 切片

        hls_path        ./objs/nginx/html; # 【新增】HLS 文件生成目录，与 http_server.dir 对应

        hls_fragment    4; # 【新增】单个 TS 切片目标长度，单位秒

        hls_window      20; # 【新增】m3u8 播放列表保留的时间窗口，单位秒
    }


    # ========================================================
    # 业务回调 HTTP Callback
    # ========================================================

    http_hooks {
        enabled         on;

        # 主播真正开始推流
        on_publish 			http://host.docker.internal:8888/api/v1/app/live/hook/publish?hook_token=$SRS_HOOK_TOKEN;

        # 主播停止/断开推流
		on_unpublish		http://host.docker.internal:8888/api/v1/app/live/hook/unpublish?hook_token=$SRS_HOOK_TOKEN;
    }
}
